stages:
#  - test
  - build
  - push
  - deploy

variables:
  DOCKER_REGISTRY: localhost:5050
  IMAGE_TAG: "$DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"

default:
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY

#test:
#  stage: test
#  script:
#    - echo "Running health check..."
#    - docker-compose -f docker-compose.yml up -d database
#    - sleep 10
#    - curl --fail http://localhost:5000/health || (echo "Health check failed" && exit 1)
#  tags: [production-like]
#

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG app
  tags: [production-like]

push:
  stage: push
  script:
    - docker push $IMAGE_TAG
  tags: [production-like]
  after_script:
    - echo "Cleaning up local Docker image..."
    - docker rmi $IMAGE_TAG || true
  tags: [production-like]
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - docker container rm -f application || true
    - docker images | grep "$DOCKER_REGISTRY/$CI_PROJECT_PATH" | awk '{print $3}' | xargs docker rmi -f || true
    - echo "APP_IMAGE=$IMAGE_TAG" >> .env
    - docker pull $IMAGE_TAG
    - docker compose  up -d application database
  tags: [production-like]
  only:
    - main
