stages:
  - build
  - push
  - deploy
  - post-test

variables:
  DOCKER_REGISTRY: localhost:5050
  IMAGE_TAG: "$DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"

default:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" \
        | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY
  tags: [production-like]

build:
  stage: build
  before_script: []
  script:
    - docker build -t "$IMAGE_TAG" app

push:
  stage: push
  script:
    - docker push "$IMAGE_TAG"
  after_script:
    - docker rmi "$IMAGE_TAG" || true

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - docker container rm -f application || true
    - docker images | grep "$DOCKER_REGISTRY/$CI_PROJECT_PATH" | awk '{print $3}' | xargs -r docker rmi -f
    - echo "APP_IMAGE=$IMAGE_TAG" > .env
    - docker pull "$IMAGE_TAG"
    - docker compose up -d application database
  only:
    - main

trigger_tests:
  stage: post-test
  needs: ["deploy"]
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  trigger:
    include:
      - local: ".gitlab/test-pipeline.yml"
    strategy: depend
