stages:
  - build
  - push
  - deploy
  - test

variables:
  DOCKER_REGISTRY: localhost:5050
  IMAGE_TAG: "$DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"

default:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY

build:
  stage: build
  before_script: []
  script:
    - docker build -t $IMAGE_TAG app
  tags: [production-like]

push:
  stage: push
  script:
    - docker push $IMAGE_TAG
  after_script:
    - echo "Cleaning up local Docker image..."
    - docker rmi $IMAGE_TAG || true
  tags: [production-like]
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - docker container rm -f application || true
    - docker images | grep "$DOCKER_REGISTRY/$CI_PROJECT_PATH" | awk '{print $3}' | xargs docker rmi -f || true
    - echo "APP_IMAGE=$IMAGE_TAG" >> .env
    - docker pull $IMAGE_TAG
    - docker compose  up -d application database
  tags: [production-like]
  only:
    - main

test:
  stage: test
  image: docker.arvancloud.ir/curlimages/curl:8.14.1
  before_script: []
  script:
    - echo "Checking app after deploy..."
    - curl http://localhost:5000/health
  tags: [production-like]
  only:
    - main
