---
services:
################################################# Application #################################################
#  application:
#    image: "${APP_IMAGE}"
#    container_name: application
#    hostname: application
#    restart: always
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#    environment:
#      MONGO_URI: "${MONGO_URI}"
#    ports:
#      - "5000:5000"
#    depends_on:
#      - database
#    networks:
#      - app-db
################################################# Database #################################################
  database:
    image: docker.arvancloud.ir/mongo:6.0
    container_name: database
    hostname: database
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_log:/var/log/mongodb/
      - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB: appdb
    expose:
      - "27017:27017"
    networks:
      - app-db
################################################# GitLab #################################################
  gitlab:
    image: docker.arvancloud.ir/gitlab/gitlab-ce:17.11.0-ce.0
    container_name: gitlab
    hostname: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:80'
        nginx['redirect_http_to_https'] = false
        gitlab_rails['time_zone'] = 'Tehran'
        registry_external_url 'http://localhost:5050'
        registry_nginx['redirect_http_to_https'] = false
    ports:
      - '80:80'
      - '22:22'
      - '5050:5050'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_secret:/secret/gitlab/backups
      - /etc/timezone:/etc/timezone:ro
    mem_limit: 8g
    cpus: 4.0
    networks:
      - gitlab
################################################# Runner #################################################
  runner:
    image: docker.arvancloud.ir/gitlab/gitlab-runner:v17.11.0
    container_name: runner
    hostname: runner
    restart: always
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-config/config.toml:/etc/gitlab-runner/config.toml
      - /etc/timezone:/etc/timezone:ro
    network_mode: 'host'
################################################# Grafana #################################################
  grafana:
    image: docker.arvancloud.ir/grafana/grafana:11.6.1
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3000:3000"
    networks:
      - grafana
################################################# Prometheus #################################################
  prometheus:
    image: prom/prometheus:v3.4.1
    restart: always
    container_name: prometeheus
    hostname: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9090:9090"
    networks:
      - grafana
      - app-db
################################################# Mongo Exporter #################################################
mongo-exporter:
    image: 'percona/mongodb_exporter:0.40.0'
    container_name: mongo-exporter
    hostname: mongo-exporter
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      MONGODB_URI: mongodb://myUser:myPassword@mongo:27017
    command: ["--collect-all", "--compatible-mode", "--discovering-mode"]
    expose:
    - "9216:9216"
    networks:
      - app-db

networks:
  app-db:
    name: app-db
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app-db
  gitlab:
    name: gitlab
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: gitlab
  grafana:
    name: grafana
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: grafana

volumes:
  mongo_data:
    name: mongo_data
  mongo_log:
    name: mongo_log
  gitlab_config:
    name: gitlab_config
  gitlab_logs:
    name: gitlab_logs
  gitlab_data:
    name: gitlab_data
  gitlab_secret:
    name: gitlab_secret
  runner_data:
    name: runner_data
  grafana_data:
    name: grafana_data
  prometheus_data:
    name: prometheus_data
