---
services:
################################################# Web #################################################
  application:
    image: application:6.9
    container_name: application
    hostname: application
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_URI: mongodb://database:27017/appdb
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-db
################################################# Mongo #################################################
  database:
    image: docker.arvancloud.ir/mongo:6.0
    container_name: database
    hostname: database
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-log:/var/log/mongodb/
      - /etc/timezone:/etc/timezone:ro
    expose:
      - "27017:27017"
    networks:
      - app-db
################################################# GitLab #################################################
  gitlab:
    image: docker.arvancloud.ir/gitlab/gitlab-ce:17.11.0-ce.0
    container_name: gitlab
    hostname: 'gitlab'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1'
        nginx['redirect_http_to_https'] = false
        gitlab_rails['time_zone'] = 'Tehran'
        registry_nginx['redirect_http_to_https'] = false
        registry_nginx['listen_port'] = 8050
    ports:
      - '80:80'
      - '22:22'
      - '8050:8050'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-secret:/secret/gitlab/backups
      - /etc/timezone:/etc/timezone:ro
    mem_limit: 8g
    cpus: 4.0
    networks:
      - gitlab
        ################################################## Runner #################################################
        #  runner:
        #    image: docker.arvancloud.ir/gitlab/gitlab-runner:v17.11.0
        #    container_name: runner
        #    restart: always
        #    networks: 
        #      - gitlab
        #    depends_on:
        #      - gitlab
        #    volumes:
        #      - /var/run/docker.sock:/var/run/docker.sock
        #      - runner-data:/etc/gitlab-runner
        #      - /etc/timezone:/etc/timezone:ro
        ################################################## Grafana #################################################
        #  grafana:
        #    image: grafana/grafana:11.6.1
        #    container_name: grafana
        #    restart: always
        #    user: "${UID}:${GID}" #sudo chown UID:GID grafana-data
        #    networks:
        #      - gitlab
        #    volumes:
        #      - grafana-data:/var/lib/grafana
        #      - /etc/timezone:/etc/timezone:ro
        ################################################## ElasticSearch #################################################
        #  elasticsearch:
        #    image: docker.arvancloud.ir/elasticsearch:7.9.1
        #    container_name: elasticsearch
        #    hostname: elasticsearch
        #    restart: always
        #    ports:
        #      - "9200:9200"
        #      - "9300:9300"
        #    volumes:
        #      - test-data:/usr/share/elasticsearch/data/
        #      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        #      - /etc/timezone:/etc/timezone:ro
        #    environment:
        #      - discovery.type=single-node
        #      - http.host=0.0.0.0
        #      - transport.host=0.0.0.0
        #      - xpack.security.enabled=false
        #      - xpack.monitoring.enabled=false
        #      - cluster.name=elasticsearch
        #      - bootstrap.memory_lock=true
        #    networks:
        #      - elk
        ################################################## LogStash #################################################
        #  logstash:
        #    image: docker.arvancloud.ir/logstash:7.9.1
        #    container_name: logstash
        #    hostname: logstash
        #    restart: always
        #    ports:
        #      - "5044:5044"
        #      - "9600:9600"
        #    volumes:
        #      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        #      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
        #      - ls-data:/usr/share/logstash/data
        #      - /etc/timezone:/etc/timezone:ro
        #
        #    networks:
        #      - elk
        #    depends_on:
        #      - elasticsearch
        ################################################## Kibana #################################################
        #  kibana:
        #    image: docker.arvancloud.ir/kibana:7.9.1
        #    container_name: kibana
        #    hostname: kibana
        #    restart: always
        #    ports:
        #      - "5601:5601"
        #    volumes:
        #      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        #      - kb-data:/usr/share/kibana/data
        #      - /etc/timezone:/etc/timezone:ro
        #    networks:
        #      - elk
        #    depends_on:
        #      - elasticsearch

networks:
  app-db:
    name: app-db
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app-db
  gitlab:
    name: gitlab
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: gitlab

volumes:
  mongo-data:
  mongo-log:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-secret:
