---
services:
################################################# Application #################################################
  application:
    image: application:6.9
    container_name: application
    hostname: application
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_URI: mongodb://lifeweb:It5~TPn04p1-eTAH@database:27017/appdb?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-db
################################################# Database #################################################
  database:
    image: docker.arvancloud.ir/mongo:6.0
    container_name: database
    hostname: database
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_log:/var/log/mongodb/
      - /etc/timezone:/etc/timezone:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: lifeweb
      MONGO_INITDB_ROOT_PASSWORD: It5~TPn04p1-eTAH
    expose:
      - "27017:27017"
    networks:
      - app-db
################################################# GitLab #################################################
  gitlab:
    image: docker.arvancloud.ir/gitlab/gitlab-ce:17.11.0-ce.0
    container_name: gitlab
    hostname: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        nginx['redirect_http_to_https'] = false
        gitlab_rails['time_zone'] = 'Tehran'
        registry_external_url 'http://gitlab:5050'
        registry_nginx['redirect_http_to_https'] = false
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_secret:/secret/gitlab/backups
      - /etc/timezone:/etc/timezone:ro
    mem_limit: 8g
    cpus: 4.0
    networks:
      - gitlab
################################################# Runner #################################################
  runner:
    image: docker.arvancloud.ir/gitlab/gitlab-runner:v17.11.0
    container_name: runner
    hostname: runner
    restart: always
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-config:/etc/gitlab-runner
      - /etc/timezone:/etc/timezone:ro
    networks: 
      - gitlab
################################################# Grafana #################################################
  grafana:
    image: docker.arvancloud.ir/grafana/grafana:11.6.1
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3000:3000"
    networks:
      - gitlab

networks:
  app-db:
    name: app-db
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app-db
  gitlab:
    name: gitlab
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: gitlab

volumes:
  mongo_data:
    name: mongo_data
  mongo_log:
    name: mongo_log
  gitlab_config:
    name: gitlab_config
  gitlab_logs:
    name: gitlab_logs
  gitlab_data:
    name: gitlab_data
  gitlab_secret:
    name: gitlab_secret
  runner_data:
    name: runner_data
  grafana_data:
    name: grafana_data
