concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "arvan-academy"
  url = "https://gitlab.mhesfahani.ir"
  id = 3
  token = "glrt-ZzozCm86MQp0OjIKdTox6WUgR72HqyDXGd4JRYxnERA.1708ls0l4"
  token_obtained_at = 2025-05-11T10:34:58Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/builds:/builds"]
    pull_policy = ["if-not-present"]
    shm_size = 0
    network_mtu = 0

