concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800


[[runners]]
  name = "lifeweb"
  url = "http://gitlab"
  id = 0
  token = "glrt-dDoxCnU6McB8WCjiInIsf4R_Rmpdp2EQ.0w0mtktob"
  token_obtained_at = 2025-06-17T09:52:58Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    Type = "filesystem"
    Path = "/cache"
    Shared = true
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker.arvancloud.ir/docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/builds:/builds"]
    pull_policy = ["if-not-present"]
    shm_size = 256
    network_mtu = 0
