concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "lifeweb"
  url = "http://gitlab"
  id = 0
  token = "glrt-dDoxCnU6MU8tbfvcoaGmKHyU7Dis41kQ.0w0angxr5"
  token_obtained_at = 2025-06-16T06:58:09Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    Type = "filesystem"
    Path = "/cache"
    Shared = true
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/builds:/builds"]
    pull_policy = ["if-not-present"]
    shm_size = 256
    network_mtu = 0
