stages:
  - test

test:
  stage: test
  image: docker.arvancloud.ir/curlimages/curl:8.14.1
  before_script: []
  script:
    - echo "Checking app after deploy..."
    - curl http://localhost:5000/health
  tags: [production-like]

